# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nathan Walters
name: Nathan Walters
email: nwalters512@gmail.com
description: >
  The personal website of Nathan Walters
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nwalters.com" # the base hostname & protocol for your site
twitter_username: waltersn512
github_username:  nwalters512

# Build settings
markdown: kramdown

permalink: /blog/:categories/:year/:month/:day/:title

exclude:
  - node_modules/

sass:
  load_paths:
    - _sass
    - _assets/vendor
    - _assets/vendor/bootstrap-sass/assets/stylesheets

kramdown:
  parse_block_html: true

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  - firebase.json
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - node_modules

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
